(Mtc) Change SDP to be set only by MtcSession#SetSdpToSend
All Early States let MtcSession set FormSdp internally with its current CallType while Established and Updating States call FormSdp() before they call IMtcSession#Update or IMtcSession#AcceptUpdate. It
ruins the consistency and is making some redundant logics.
This commit changes Update() and AcceptUpdate() calls FormSdp()
appropriately and the callers set only the target CallType through
IMtcSession#SetCallType so that it can be used for FormSdp().
Also, make a new API IMtcSession#GetPreviousCallType because
UpdatingInfo uses GetCallType() which doesn't return the previous
CallType but the new CallType when a SIP message is received.

Exception: This commit doesn't handle about the case of
EstablishedState#FormAutoAccept.

Bug: 274840426
Test: atest ImsStackNativeEnablerMtcTests
Test: upgrade and incoming upgrade.
Change-Id: Icbfafd0f1d21efd2d478ccb9551e16012c087d52